spring:
  application:
    # 服务名称尽量用-,不要用_,不要用特殊字符
    name: content-center
  datasource:
    #    url: jdbc:mysql://112.74.99.22:3306/content_center?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    url: jdbc:mysql://112.74.99.22:3306/content_center?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    hikari:
      username: root
      password: cyh.99
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 47.100.1.18:8848

  #    sentinel:
  #      transport:
  #        # 指定sentinel控制台地址
  #        dashboard: localhost:8080

  main:
    allow-bean-definition-overriding: true

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  # 饥饿加载
  eager-load:
    clients: user-center
    enabled: true

logging:
  level:
    com.soft1851.content.feignclient.UserCenterFeignClient: debug

#feign:
#  client:
#    config:
#      # 全局配置
#      user-center:
#        loggerLevel: full

feign:
  sentinel:
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
      # 配置feign的拦截器，让token可以在各个微服务之间传递
      requestInterceptors:
        - com.soft1851.content.feignclient.interceptor.TokenInterceptor

  httpclient:
    # 让feign使用Apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
#feign:
#  client:
#    config:
#      user-center:
#        loggerLevel:full
rocketmq:
  name-server: 112.74.99.22:9876
  producer:
    group: test-group

jwt:
  secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  # 有效期，单位秒，默认2周
  exprice-time-in-second: 1209600