spring:
  application:
    # 服务名称尽量用-,不要用_,不要用特殊字符
    name: content-center
  datasource:
    url: jdbc:mysql://112.74.99.22:3306/content_center
    hikari:
      username: root
      password: cyh.99
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 112.74.99.22:8848
#        namespace: 88d8b2d3-f5e9-48ce-a1d2-f42c6fd62997
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  # 饥饿加载
  eager-load:
    clients: user-center
    enabled: true
