server:
  port: 8082

spring:
  application:
    name: course-center
  datasource:
    #    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://112.74.99.22:3306/course_center?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: cyh.99
#      max-lifetime: 30000
#      minimum-idle: 1
#      maximum-pool-size: 20
#      auto-commit: true
#      idle-timeout: 10000
#      connection-timeout: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
