spring:
  application:
    # 服务名称尽量用-,不要用_,不要用特殊字符
    name: user-center
  datasource:
    url: jdbc:mysql://112.74.99.22:3306/user_center?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    hikari:
      username: root
      password: cyh.99
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 47.100.1.18:8848
server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

rocketmq:
  name-server: 112.74.99.22:9876
  producer:
    group: test-group
