spring:
  application:
    # 服务名称尽量用-,不要用_,不要用特殊字符
    name: user-center
  datasource:
    #    url: jdbc:mysql://112.74.99.22:3306/user_center?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    url: jdbc:mysql://112.74.99.22:3306/user_center?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    hikari:
      username: root
      password: cyh.99
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 47.100.1.18:8848
  zipkin:
    base-url: http://112.74.99.22:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      # 抽样率，默认是0.1（10%）
      probability: 1.0
server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

rocketmq:
  name-server: 112.74.99.22:9876
  producer:
    group: test-group

jwt:
  secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  # 有效期，单位秒，默认2周
  exprice-time-in-second: 1209600