server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.1.18:8848
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他为服务
          enabled: true
      routes:
        - id: path_user
          uri: lb://user-center
          predicates:
            #            - TimeBetween=下午9:00,下午6:00
            #            - After=2020-10-09T10:40:00+00:00[Asia/Shanghai]
            - Path=/users/**
        #            - Weight=group1,8
        #        - id: path_user_low
        #          uri: lb://user-center/user/one/{id}
        #          predicates:
        #            - After=2020-10-09T10:00:00+00:00[Asia/Shanghai]
        #            - Weight=group1,2
        #            - Path=/user/**
        - id: path_share
          uri: lb://content-center
          predicates:
            - Path=/shares/**
        - id: path_notice
          uri: lb://content-center
          predicates:
            - Path=/notices/**
        - id: Path_admin_share
          uri: lb://content-center
          predicates:
            - Path=/admin/shares/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: trace
